name: check
on:
  push:
    branches: [main]
  pull_request:
jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake check --print-build-logs
      - run: nix fmt -- --ci
